name: CI_Deploy

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: subekti13/simple-express:${{ steps.previoustag.outputs.tag }}
  
  deploy-to-portainer:
    needs: build-and-push-docker 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 

      - name: Deploy Stack
        uses: subekti404dev/portainer-stack-deployment@v1
        with:
          portainer-url: ${{ secrets.PORTAINER_HOST }}
          portainer-username: ${{ secrets.PORTAINER_USERNAME }}
          portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
          portainer-endpoint: 2
          name: simple-express
          file: stackfile.yml.mustache
          variables: '{"image": "subekti13/simple-express:${{ steps.previoustag.outputs.tag }}"}'
